services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
#  ollama:
#    image: ollama/ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./ollama_data:/root/.ollama
#    restart: always
#  mcp-server:
#    build: .
#    depends_on:
#      - rabbitmq
#      - ollama
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - iam_url=${iam_url}
#      - iam_username=${iam_username}
#      - iam_password=${iam_password}
#      - ts_api_url=${ts_api_url}

volumes:
  rabbitmq_data:
